//! # rpn2 — math expressions to binary RPN bytecode
//!
//! Compile a mathematical expression (as `&str`) into compact binary
//! Reverse-Polish-Notation bytecode, written into a caller-provided
//! buffer. Built for live recompilation: zero allocation, no panics,
//! bounded everything.
//!
//! ```
//! use rpn2::{decode_into, parse_into, MAX_RPN};
//!
//! let mut buf = [0u8; MAX_RPN];
//! let n = parse_into("3x+2", &mut buf).unwrap();
//! assert_eq!(n, 22); // 22 bytes of binary bytecode
//!
//! // Human-readable rendering of the same bytes:
//! let mut text = [0u8; 4 * MAX_RPN];
//! let m = decode_into(&buf[..n], &mut text).unwrap();
//! assert_eq!(&text[..m], b"3 x * 2 +");
//! ```
//!
//! ## Contract
//!
//! * **Input**: ASCII expression — numbers (`12`, `.5`, `1e-3`), variables
//!   `a..z`, constants `e`/`pi`, functions `sin cos tan asin acos atan ln log`,
//!   operators `+ - * / ^`, unary minus, implicit multiplication (`3x`,
//!   `2sin(x)`), and log-with-base via postfix underscore: `log(100)_10`.
//! * **Output**: little-endian opcode stream (see [`opcodes`]) with
//!   fixed-width instructions — O(1) to skip or decode any instruction.
//!   Hard-capped at [`MAX_RPN`] bytes; larger compilations are rejected
//!   with [`Error::OutputLimitExceeded`] regardless of buffer size.
//! * **Failure modes are values, not crashes**: malformed input yields
//!   [`Error`] with the offending byte offset; nesting beyond
//!   [`MAX_DEPTH`] yields [`Error::TooDeep`]; a too-small buffer yields
//!   [`Error::BufferTooSmall`]. Nothing panics; nothing allocates.
//!
//! ## Performance shape
//!
//! Single fused pass: O(n) time, O(1) auxiliary memory (a fixed
//! operator stack), direct-to-buffer emission. The lexer uses a hybrid
//! scalar/SIMD scanner (SSE2 / NEON where baseline, portable scalar
//! elsewhere) and a bit-exact fast float path; see the README for
//! measured figures.

#![no_std]
#![deny(unsafe_code)]

#[cfg(test)]
extern crate std;

pub mod opcodes;

mod class;
mod core;
mod decode;
mod error;
mod lex;
mod num;
mod simd;
mod writer;

pub use core::parse_into;
pub use decode::decode_into;
pub use error::{Error, Result};

/// Hard cap on generated bytecode output, in bytes.
///
/// A compilation whose bytecode would exceed this fails with
/// [`Error::OutputLimitExceeded`] even if the caller's buffer is larger:
/// bigger than this is simply too much expression.
pub const MAX_RPN: usize = 10 * 1024;

/// Maximum expression nesting depth (parentheses, function calls,
/// unary chains, `^` and `_base` stacking).
///
/// Nesting costs no output bytes, so a bound independent of [`MAX_RPN`]
/// is required to keep memory use flat. Valid expressions beyond this
/// depth fail with [`Error::TooDeep`].
pub const MAX_DEPTH: u32 = 128;

// Compile-time sanity checks on the public limits.
const _: () = {
    assert!(MAX_RPN == 10 * 1024);
    assert!(MAX_DEPTH >= 16);
};

#[cfg(test)]
mod tests {
    #[test]
    fn readme_example_is_true() {
        let mut buf = [0u8; crate::MAX_RPN];
        let n = crate::parse_into("atan(2)x + log(8)_2", &mut buf).unwrap();
        let mut text = [0u8; 4 * crate::MAX_RPN];
        let m = crate::decode_into(&buf[..n], &mut text).unwrap();
        assert_eq!(&text[..m], b"2 atan x * 8 log 2 logb +");
    }
}
